const { colors, fontFamily, radii } = require('./src/styles/tokens');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: colors.primary,
        'primary-strong': colors.primaryStrong,
        'primary-soft': colors.primarySoft,
        bg: colors.bg,
        surface: colors.surface,
        ink: colors.ink,
        muted: colors.muted,
        subtle: colors.subtle,
        line: colors.line,
        success: colors.success,
        'success-strong': colors.successStrong,
        'success-soft': colors.successSoft,
        'success-tint': colors.successTint,
        warning: colors.warning,
        'warning-strong': colors.warningStrong,
        'warning-soft': colors.warningSoft,
        'warning-tint': colors.warningTint,
        'amber-soft': colors.amberSoft,
        cream: colors.cream,
        'cream-line': colors.creamLine,
        danger: colors.danger,
        'danger-strong': colors.dangerStrong,
        'danger-soft': colors.dangerSoft,
        'danger-tint': colors.dangerTint,
        'danger-line': colors.dangerLine,
      },
      fontFamily: {
        display: [fontFamily.display],
        'display-xl': [fontFamily.displayExtraBold],
        body: [fontFamily.body],
        'body-medium': [fontFamily.bodyMedium],
        'body-semibold': [fontFamily.bodySemiBold],
        'body-bold': [fontFamily.bodyBold],
        mono: [fontFamily.mono],
        'mono-bold': [fontFamily.monoBold],
      },
      borderRadius: {
        sm: `${radii.sm}px`,
        md: `${radii.md}px`,
        lg: `${radii.lg}px`,
        xl: `${radii.xl}px`,
      },
    },
  },
  plugins: [],
};
